channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.2
  - biopython=1.83
  - dash=2.16.1
  - dash-ag-grid=2.4.0
  - h5py=3.10.0
  - networkx=3.2.1
  - pandas=2.2.1
  - plotly=5.22.0
  - scipy=1.12.0
  - waitress=3.0.0
  - numpy=1.26.4
